import { Listing } from "@/types/Listing";

export const dummyListings: Listing[] = [
  {
    id: "1",
    title: "Crew Pad – Heathrow",
    description: "A cosy private room just 10 mins from LHR with fast Wi-Fi and 24/7 access.",
    location: "London, UK (LHR)",
    airportCode: "LHR",
    hostId: "host_001",
    listing_type: "private_room",
    beds: 1,
    bathrooms: 1,
    price_per_night: 85,
    price_per_week: 500,
    available_from: "2025-08-05",
    available_to: "2025-12-31",
    amenities: ["wifi", "kitchen", "heating", "parking"],
    image_url: "/images/apartment.jpg",
    coords: [-0.4543, 51.47], // [lng, lat] Heathrow
    created_at: "2025-08-01",
    updated_at: "2025-08-01",
  },
  {
    id: "2",
    title: "Crew Crashpad – Stansted",
    description: "Comfortable private room ideal for Ryanair crew. Flexible dates and all bills included.",
    location: "Stansted, UK (STN)",
    airportCode: "STN",
    hostId: "host_002",
    listing_type: "private_room",
    beds: 2,
    bathrooms: 1,
    price_per_night: 40,
    price_per_month: 950,
    available_from: "2025-08-10",
    available_to: "2026-01-15",
    amenities: ["wifi", "laundry", "shared lounge"],
    image_url: "/images/bedroom.jpg",
    coords: [0.235, 51.885], // [lng, lat] Stansted
    created_at: "2025-08-02",
    updated_at: "2025-08-02",
  },
  {
    id: "7",
    title: "Private Room – Stansted",
    description: "Comfortable private room near STN airport with fast Wi-Fi and flexible booking options.",
    location: "Stansted, UK (STN)",
    airportCode: "STN",
    hostId: "host_007",
    listing_type: "private_room",
    beds: 1,
    bathrooms: 1,
    price_per_night: 55,
    price_per_week: 320,
    available_from: "2025-08-15",
    available_to: "2026-02-28",
    amenities: ["wifi", "heating", "parking"],
    image_url: "/images/bedroom.jpg",
    coords: [0.235, 51.885], // [lng, lat] Stansted
    created_at: "2025-08-05",
    updated_at: "2025-08-05",
  },
  {
    id: "3",
    title: "Entire Flat – Gatwick",
    description: "Self-contained modern apartment, 15 min drive to LGW. Perfect for long stays.",
    location: "Gatwick, UK (LGW)",
    airportCode: "LGW",
    hostId: "host_003",
    listing_type: "entire_place",
    beds: 1,
    bathrooms: 1,
    price_per_night: 120,
    price_per_week: 700,
    price_per_month: 2400,
    available_from: "2025-08-15",
    available_to: "2026-02-01",
    amenities: ["wifi", "kitchen", "tv", "balcony"],
    image_url: "/images/living-room.jpg",
    coords: [-0.1821, 51.1537], // [lng, lat] Gatwick
    created_at: "2025-08-03",
    updated_at: "2025-08-03",
  },
  {
    id: "4",
    title: "Private Room – Luton",
    description: "Quiet room near LTN with easy access to public transport. Great for solo travelers.",
    location: "Luton, UK (LTN)",
    airportCode: "LTN",
    hostId: "host_004",
    listing_type: "private_room",
    beds: 1,
    bathrooms: 1,
    price_per_night: 60,
    price_per_week: 350,
    available_from: "2025-09-01",
    available_to: "2026-01-31",
    amenities: ["wifi", "heating", "parking"],
    image_url: "/images/apartment.jpg",
    coords: [-0.3683, 51.8747], // [lng, lat] Luton
    created_at: "2025-08-10",
    updated_at: "2025-08-10",
  },
  {
    id: "5",
    title: "Private Room – Manchester",
    description: "Affordable private room close to MAN airport. Perfect for short stays and flexible bookings.",
    location: "Manchester, UK (MAN)",
    airportCode: "MAN",
    hostId: "host_005",
    listing_type: "private_room",
    beds: 2,
    bathrooms: 1,
    price_per_night: 45,
    price_per_month: 900,
    available_from: "2025-09-05",
    available_to: "2026-03-01",
    amenities: ["wifi", "laundry", "shared lounge"],
    image_url: "/images/bedroom.jpg",
    coords: [-2.2749, 53.3651], // [lng, lat] Manchester
    created_at: "2025-08-15",
    updated_at: "2025-08-15",
  },
  {
    id: "6",
    title: "Entire Apartment – Dublin",
    description: "Modern apartment in Dublin city center, 20 min drive to DUB. Ideal for longer stays.",
    location: "Dublin, Ireland (DUB)",
    airportCode: "DUB",
    hostId: "host_006",
    listing_type: "entire_place",
    beds: 2,
    bathrooms: 1,
    price_per_night: 130,
    price_per_week: 800,
    price_per_month: 2600,
    available_from: "2025-09-10",
    available_to: "2026-04-01",
    amenities: ["wifi", "kitchen", "tv", "balcony"],
    image_url: "/images/living-room.jpg",
    coords: [-6.2701, 53.4213], // [lng, lat] Dublin
    created_at: "2025-08-20",
    updated_at: "2025-08-20",
  },
];
